- name: Setup Intrusion Prevention System with Fail2ban and ModSecurity
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - fail2ban
          - libapache2-mod-security2
        state: present
        update_cache: yes

    - name: Configure ModSecurity
      template:
        src: templates/modsecurity.conf.j2
        dest: "/etc/modsecurity/modsecurity.conf"
      notify: Restart Apache

    - name: Configure Fail2ban jails
      template:
        src: templates/jail.local.j2
        dest: "/etc/fail2ban/jail.local"
      notify: Restart Fail2ban

    - name: Create Fail2ban filter for ModSecurity
      template:
        src: templates/modsec.conf.j2
        dest: "/etc/fail2ban/filter.d/modsec.conf"
      notify: Restart Fail2ban

  handlers:
    - name: Restart Apache
      service:
        name: "apache2"
        state: restarted

    - name: Restart Fail2ban
      service:
        name: fail2ban
        state: restarted
