---
- name: Install and Configure ModSecurity for Apache2
  hosts: all
  become: yes

  vars:
    modsecurity_conf_path: /etc/modsecurity/modsecurity.conf

  tasks:
    - name: Install and enable ModSecurity
      block:
        - name: Install libapache2-mod-security2
          apt:
            name: libapache2-mod-security2
            state: present
            update_cache: yes

        - name: Ensure ModSecurity is enabled
          apache2_module:
            name: security2
            state: present
      notify: Restart Apache

    - name: Configure ModSecurity
      block:
        - name: Copy ModSecurity configuration file
          copy:
            src: "{{ modsecurity_conf_path }}-recommended"
            dest: "{{ modsecurity_conf_path }}"
            remote_src: yes

        - name: Enable SecAuditEngine
          lineinfile:
            path: "{{ modsecurity_conf_path }}"
            regexp: "^SecAuditEngine"
            line: "SecAuditEngine On"
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
